# Generated by Django 6.0.7 on 2026-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FounderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mitanshu M. Upadhyay', max_length=200)),
                ('title', models.CharField(default='BAMS Student & Founder, Sattvica Ayurved', max_length=200)),
                ('bio', models.TextField(default='Mitanshu M. Upadhyay is a BAMS student and innovation enthusiast at the intersection of Artificial Intelligence, Ayurveda, and Wearable Technology. As the founder of Sattvica Ayurved, he is pioneering the fusion of ancient healing wisdom with cutting-edge technology to make personalized Ayurvedic wellness accessible to everyone.')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/')),
                ('email', models.EmailField(blank=True, default='mitanshu@sattvicaayurved.com', max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='founder/')),
            ],
            options={
                'verbose_name': 'Founder Profile',
                'verbose_name_plural': 'Founder Profile',
            },
        ),
    ]
