from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import DemoSubmission
from .forms import DemoForm
from .utils import generate_dummy_report


def demo(request):
    """
    GET: Display the demo input form.
    POST: Validate form, generate dummy report, save to DB, redirect to results.
    """
    if request.method == 'POST':
        form = DemoForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            age = form.cleaned_data['age']
            gender = form.cleaned_data['gender']

            # Generate dummy Ayurvedic report (swap this for real ML later)
            report = generate_dummy_report(name, age, gender)

            # Save to database
            submission = DemoSubmission.objects.create(
                name=name,
                age=age,
                gender=gender,
                vata_score=report['vata_score'],
                pitta_score=report['pitta_score'],
                kapha_score=report['kapha_score'],
                stress_score=report['stress_score'],
                sleep_score=report['sleep_score'],
                energy_score=report['energy_score'],
                wellness_score=report['wellness_score'],
            )

            return redirect('demo:results', pk=submission.pk)
    else:
        form = DemoForm()

    context = {
        'form': form,
        'demo_next_steps': [
            'Your data is processed by our AI engine',
            'Vata, Pitta & Kapha scores are calculated',
            'Personalized lifestyle & diet suggestions generated',
            'Full wellness dashboard displayed instantly',
        ],
        'page_title': 'NADI-VERSE™ Demo | Discover Your Dosha',
        'meta_description': 'Take the NADI-VERSE™ interactive demo to discover your Ayurvedic dosha profile. SSIP conceptual demonstration.',
    }
    return render(request, 'demo/demo.html', context)


def results(request, pk):
    """
    Display the dummy Ayurvedic wellness report for a given submission.
    """
    submission = get_object_or_404(DemoSubmission, pk=pk)

    # Re-generate suggestions (not stored in DB to keep model lean)
    report = generate_dummy_report(submission.name, submission.age, submission.gender)

    context = {
        'submission': submission,
        'suggestions': report['suggestions'],
        'dominant_dosha': report['dominant_dosha'],
        'page_title': f'Your Ayurvedic Report — NADI-VERSE™',
        'meta_description': 'Your personalized Ayurvedic wellness report generated by NADI-VERSE™ AI demo.',
    }
    return render(request, 'demo/results.html', context)
