# Generated by Django 6.0.7 on 2026-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('vata_score', models.IntegerField()),
                ('pitta_score', models.IntegerField()),
                ('kapha_score', models.IntegerField()),
                ('stress_score', models.IntegerField()),
                ('sleep_score', models.IntegerField()),
                ('energy_score', models.IntegerField()),
                ('wellness_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demo Submission',
                'verbose_name_plural': 'Demo Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
